server:
  port: 8001
spring:
  application:
    name: spring-boot-activemq
  activemq:
    broker-url: tcp://127.0.0.1:61616
    user: user
    password: user

  jms:
    # JMS的发布订阅配置，在消费者端起作用，生产者可以直接指定是向队列发还是Topic发
    # false 代表使用Queue
    # true 代表使用Topic
    pub-sub-domain: true

# 自定义队列名称
queue-name: my-springboot-queue
# 自定义Topic名称
topic-name: my-springboot-topic